apiVersion: v1
kind: Namespace
metadata:
  name: cluster-api-provider-exoscale-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: cluster-api-provider-exoscale-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller-manager
  template:
    metadata:
      labels:
        app: controller-manager
    spec:
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: ghcr.io/lucj/exoscale-capi-provider # replaced by kustomize image override
          command: ["/manager"]
          envFrom:
            - secretRef:
                name: exoscale-credentials
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
