resources:
  - bases/infrastructure.cluster.x-k8s.io_exoscaleclusters.yaml
  - bases/infrastructure.cluster.x-k8s.io_exoscaleclustertemplates.yaml
  - bases/infrastructure.cluster.x-k8s.io_exoscalemachines.yaml
  - bases/infrastructure.cluster.x-k8s.io_exoscalemachinetemplates.yaml
